name: Auto-triage
on:
  issues:
    types: [labeled, unlabeled, opened, edited]

jobs:
  auto-assign:
    name: "Auto-assign issue"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Building Action
        run: npm install
        working-directory: ./.github/actions/auto-assign

      - name: "Run the action (assign issues)"
        uses: ./.github/actions/auto-assign
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
